My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login_app.urls'))
]

My_Second_Project/login_app/urls.py
from django.conf.urls import url
from django.urls import path
from login_app import views
from django.conf import  settings
from django.contrib.staticfiles.urls import  static,staticfiles_urlpatterns
app_name ='login_app'
urlpatterns = [

    path('',views.home,name='home'),
    path('register/',views.register,name='register'),
    path('login/',views.login_page,name='login_page'),
    path('user_login/',views.user_login,name = 'user_login'),
    path('user_logout/',views.user_logout,name='user_logout'),

]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Second_Project/login_app/models.py
from django.db import models
from django.contrib.auth.models import  User
# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    facebook_id = models.URLField()
    profile_pic = models.ImageField(upload_to ='profile_pics',blank = True)

    def __str__(self):
        return self.user.username

My_Second_Project/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password','email')

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('facebook_id','profile_pic')

My_Second_Project/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserInfoForm
from login_app.models import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def home(request):
    dict={}
    if request.user.is_authenticated:
        current_user = request.user;
        user_id = current_user.id;
        user_basic_info = User.objects.get(pk=user_id);
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict ={'user_basic_info':user_basic_info,'user_more_info':user_more_info}
    return render(request,'login_app/home.html',context=dict)

def login_page(request):
    dict ={'title':'Login'}
    return render(request,'login_app/login.html',context=dict)

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('login_app:home'))
            else:
                return HttpResponse("User Is Not Active")
        else:
            return HttpResponse("UserName or Password Doesn't Match")
    else:
        return HttpResponseRedirect(reverse('login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_app:home'))


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        user_info_form = UserInfoForm(data = request.POST)
        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            user_info.save()
            registered = True
    else:
        user_form = UserForm()
        user_info_form  = UserInfoForm()
    dict = {'title':'Register','user_form':user_form,'user_info_form':user_info_form,'registered':registered}
    return render(request,'login_app/register.html',context=dict)

My_Second_Project/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<ul class="navbar-nav">
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'login_app:home' %}">Home</a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'login_app:user_logout' %}">Log Out</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'login_app:register' %}">Register</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'login_app:login_page' %}">Log In</a>
  </li>
  {% endif %}
</ul>
</nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
  </body>
</html>

My_Second_Project/templates/login_app/home.html
{% extends 'login_app/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<p>Hi, {{ user_basic_info.username }}</p>
<p>Email: {{ user_basic_info.email }}</p>
<p> <a href=" {{ user_more_info.facebook_id }} ">Facebook Profile</a> </p>
<img src="/media/{{ user_more_info.profile_pic }}" alt="" width="800px" height="auto" >
{% else %}
<div class="alert alert-danger"><h2>You are Not Logged IN!!!!</h2></div>
{% endif %}
{% endblock %}

My_Second_Project/templates/login_app/login.html
{% extends 'login_app/base.html' %}
{% block body_block %}
<h2>Login Page</h2>
<form action="{% url 'login_app:user_login' %}" method="POST">
  <label for="username"> <i><b> User Name:<b> </i> </label>
  <input type="text" name="username" placeholder="Enter Username...." class="form-control">
  <br>
  <label for="password"> <i> <b>Password:<b></i> </label>
  <input type="password" name="password" placeholder="Enter Password" class="form-control">
  <br>
  {% csrf_token %}
  <input type="submit" name="submit" value="Log In" class='btn btn-primary btn-sm'>
</form>
{% endblock %}

My_Second_Project/templates/login_app/register.html
{% extends 'login_app/base.html' %}
{% load static %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success"><h2>Registration Successful</h2></div>
{% else %}
<h2>Register</h2>
<form enctype="multipart/form-data"  method="POST">
  {{ user_form.as_p }}
  {{ user_info_form.as_p }}
  {% csrf_token %}
  <br>
<input type="submit" name="submit" value="LogIn" class='btn btn-primary btn-sm'>
</form>
{% endif %}
{% endblock %}